localaddr = ":7653"
#resolveraddr = "[::1]:7777"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
dbconn = "%%DATABASE_URL%%"

[servertls]
type = "dev"

[clienttls]
type = "dev"