localaddr = ":0"
#localaddr = ":7653"
domains = ["ubmedia"]
#resolveraddr = "[::1]:7777"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
dbconn = "%%DATABASE_URL%%"
#pa.2dc77c77c6c8b703.c64ea72702e2b121

[servertls]
type = "minivault"
initialtimeout = "1h"
[servertls.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd4718f27de0f3b.4f93b0cbbf2d5ef1" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["ubmedia.mediaserverdb"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "server_cert"
dnss = ["ubmedia.mediaserverproto.Database"]
uris = []
ips = []
certinterval = "8m"
certttl = "10m"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[miniresolverclienttls]
type = "minivault"
initialtimeout = "1h"
[miniresolverclienttls.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd4718f27de0f3b.4f93b0cbbf2d5ef1" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["ubmedia.mediaserverdb"]
tokeninterval = "2m"
tokenttl = "4m"
certtype = "client_cert"
dnss = []
uris = ["grpc:miniresolverproto.MiniResolver"]
ips = []
certinterval = "1m"
certttl = "30s"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserverpg"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
